grails-app/domain/eventsplanningsystem/Event.groovy
package eventsplanningsystem

class Event {

    enum Repeat{
        ONCE('Once'), DAILY('Daily'), WEEKLLY('Weekly'), MONTHLY('Monthly'), YEARLY('Yearly')

        final String value
        Repeat(String value) {
            this.value = value
        }

        String toString() {
            value
        }
    }

    String title
    String description
    Date date
    Repeat repeat


    static belongsTo = [user : User]

    static constraints = {
        title (blank: false)
        description (blank: true)
        date (blank: false)
        repeat (blank: false)
        repeat enumType: 'ordinal'
    }
}

grails-app/domain/eventsplanningsystem/Role.groovy
package eventsplanningsystem

class Role {

    String authority

    static mapping = {
        cache true
    }

    static constraints = {
        authority blank: false, unique: true
    }
}

grails-app/domain/eventsplanningsystem/User.groovy
package eventsplanningsystem

class User {

	transient springSecurityService

	String username
	String password
	boolean enabled = true
	boolean accountExpired
	boolean accountLocked
	boolean passwordExpired

    static hasMany = {event : Event}

	static transients = ['springSecurityService']

	static constraints = {
		username blank: false, unique: true
		password blank: false
	}

	static mapping = {
		password column: '`password`'
	}

	Set<Role> getAuthorities() {
		UserRole.findAllByUser(this).collect { it.role } as Set
	}

	def beforeInsert() {
		encodePassword()
	}

	def beforeUpdate() {
		if (isDirty('password')) {
			encodePassword()
		}
	}

	protected void encodePassword() {
		password = springSecurityService.encodePassword(password)
	}
}

grails-app/domain/eventsplanningsystem/UserRole.groovy
package eventsplanningsystem

import org.apache.commons.lang.builder.HashCodeBuilder

class UserRole implements Serializable {

    private static final long serialVersionUID = 1

    User user
    Role role

    boolean equals(other) {
        if (!(other instanceof UserRole)) {
            return false
        }

        other.user?.id == user?.id &&
                other.role?.id == role?.id
    }

    int hashCode() {
        def builder = new HashCodeBuilder()
        if (user) builder.append(user.id)
        if (role) builder.append(role.id)
        builder.toHashCode()
    }

    static UserRole get(long userId, long roleId) {
        UserRole.where {
            user == User.load(userId) &&
                    role == Role.load(roleId)
        }.get()
    }

    static UserRole create(User user, Role role, boolean flush = false) {
        new UserRole(user: user, role: role).save(flush: flush, insert: true)
    }

    static boolean remove(User u, Role r, boolean flush = false) {

        int rowCount = UserRole.where {
            user == User.load(u.id) &&
                    role == Role.load(r.id)
        }.deleteAll()

        rowCount > 0
    }

    static void removeAll(User u) {
        UserRole.where {
            user == User.load(u.id)
        }.deleteAll()
    }

    static void removeAll(Role r) {
        UserRole.where {
            role == Role.load(r.id)
        }.deleteAll()
    }

    static mapping = {
        id composite: ['role', 'user']
        version false
    }
}

grails-app/controllers/eventsplanningsystem/EventController.groovy
package eventsplanningsystem

import grails.plugin.springsecurity.SpringSecurityService
import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

class EventController {
    SpringSecurityService springSecurityService
    EventService eventService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]


    def index(Integer max) {
        User user = springSecurityService.currentUser.asType(User.class)
        List<Event> todayEventsList = eventService.getEventsForDay(new Date().clearTime(), user)
        List<Event> tomorrowEventsList = eventService.getEventsForDay(new Date().clearTime().next(), user)
        if(todayEventsList?.size() == 0 && tomorrowEventsList?.size() == 0) {
            flash.error = "You don't have any events for today or tommorow. Create new event or look for events planned for another days."
        }
        respond Event.list(params), model: [todayEventsList: todayEventsList,
                tomorrowEventsList: tomorrowEventsList]
    }


    def browseday() {
        User user = springSecurityService.currentUser.asType(User.class)
        respond Event.list(params), model: [eventsList: eventService.getEventsForDay(params.date, user)]
    }


    def show(Event eventInstance) {
        flash.message = null
        respond eventInstance
    }

    def create() {
        User user = springSecurityService.currentUser.asType(User.class)
        respond new Event(), model: [user: user.getId()]
    }

    @Transactional
    def save(Event eventInstance) {
        if (eventInstance == null) {
            notFound()
            return
        }

        if (eventInstance.hasErrors()) {
            respond eventInstance.errors, view: 'create'
            return
        }
        eventInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'eventInstance.label', default: 'Event'), eventInstance.id])
                redirect eventInstance
            }
            '*' { respond eventInstance, [status: CREATED] }
        }
    }

    def edit(Event eventInstance) {
        User user = springSecurityService.currentUser.asType(User.class)
        respond eventInstance, model: [user: user.getId()]
    }

    @Transactional
    def update(Event eventInstance) {
        if (eventInstance == null) {
            notFound()
            return
        }

        if (eventInstance.hasErrors()) {
            respond eventInstance.errors, view: 'edit'
            return
        }

        eventInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Event.label', default: 'Event'), eventInstance.id])
                redirect eventInstance
            }
            '*' { respond eventInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Event eventInstance) {

        if (eventInstance == null) {
            notFound()
            return
        }

        eventInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Event.label', default: 'Event'), eventInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'eventInstance.label', default: 'Event'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/eventsplanningsystem/RegistrationController.groovy
package eventsplanningsystem

import grails.transaction.Transactional

class RegistrationController {

    static allowedMethods = [index: "GET", save: "POST"]

    def index() {
    }

    @Transactional
    def save(User userInstance) {
        if (userInstance == null) {
            notFound()
            return
        }

        if (userInstance.hasErrors()) {
            respond userInstance.errors, view: 'index'
            return
        }

        userInstance.save flush: true
        UserRole.create(userInstance, Role.findByAuthority("ROLE_USER"), true)

        redirect([controller: 'login', action: 'auth'])
    }
}

grails-app/views/event/_form.gsp
<%@ page import="eventsplanningsystem.Event" %>



<div class="fieldcontain ${hasErrors(bean: eventInstance, field: 'title', 'error')} required">
	<label for="title">
		<g:message code="event.title.label" default="Title" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="title" required="" value="${eventInstance?.title}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: eventInstance, field: 'description', 'error')} ">
	<label for="description">
		<g:message code="event.description.label" default="Description" />
		
	</label>
	<g:textField name="description" value="${eventInstance?.description}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: eventInstance, field: 'date', 'error')} required">
	<label for="date">
		<g:message code="event.date.label" default="Date" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="date" precision="minute"  value="${eventInstance?.date}"  />

</div>

<div class="fieldcontain ${hasErrors(bean: eventInstance, field: 'repeat', 'error')} required">
	<label for="repeat">
		<g:message code="event.repeat.label" default="Repeat" />
		<span class="required-indicator">*</span>
	</label>
	<g:select name="repeat" from="${eventsplanningsystem.Event$Repeat?.values()}" keys="${eventsplanningsystem.Event$Repeat.values()*.name()}" required="" value="${eventInstance?.repeat?.name()}" />

</div>

<g:hiddenField name="user" value="${user}" />

grails-app/views/event/browseday.gsp
<%@ page import="eventsplanningsystem.Event" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <title>Events for day</title>
</head>
<body>
<a href="#list-event" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index">Events List</g:link></li>
        <li><g:link class="create" action="create">New Event</g:link></li>
    </ul>
</div>

<div id="list-event" class="content scaffold-list" role="main">
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</h1>
    </g:if>
    <h1>Events for <g:formatDate format="dd.MM.yyyy" date="${params.date}" />:</div>
    <table>
        <thead>
        <tr>

            <g:sortableColumn property="title" title="${message(code: 'event.title.label', default: 'Title')}" />

            <g:sortableColumn property="description" title="${message(code: 'event.description.label', default: 'Description')}" />

            <g:sortableColumn property="date" title="${message(code: 'event.date.label', default: 'Time')}" />

            <g:sortableColumn property="repeat" title="${message(code: 'event.repeat.label', default: 'Repeat')}" />

        </tr>
        </thead>
        <tbody>
        <g:each in="${eventsList}" status="i" var="eventInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                <td><g:link action="show" id="${eventInstance.id}">${fieldValue(bean: eventInstance, field: "title")}</g:link></td>

                <td>${fieldValue(bean: eventInstance, field: "description")}</td>

                <td><g:formatDate format="HH:mm" date="${eventInstance.date}" /></td>

                <td>${fieldValue(bean: eventInstance, field: "repeat")}</td>

            </tr>
        </g:each>
        </tbody>
    </table>

    <br>
    <br>
    <h1 style="padding-left: 20px;">Choose date to browse events:</h1>
    <g:form url="[resource:event, action:'browseday']" method="GET" >
        <div class="fieldcontain required">
            <label for="date">
                <g:message default="Choose date to show events:" />
            </label>
            <g:datePicker name="date" precision="day" />
            <input type="submit" value="Show" />
        </div>
    </g:form>
</div>
</body>
</html>

grails-app/views/event/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'event.label', default: 'Event')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-event" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-event" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${eventInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${eventInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:eventInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/event/edit.gsp
<%@ page import="eventsplanningsystem.Event" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'event.label', default: 'Event')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-event" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-event" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${eventInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${eventInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:eventInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${eventInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/event/index.gsp
<%@ page import="eventsplanningsystem.Event" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'event.label', default: 'Event')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-event" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>

		<div id="list-event" class="content scaffold-list" role="main">
			<g:if test="${flash.error}">
				<div class="message" role="status">${flash.error}</div>
			</g:if>

            <g:if test="${todayEventsList?.size() > 0}">
                <h1>Events for today:</h1></div>
                <table>
                <thead>
                        <tr>

                            <g:sortableColumn property="title" title="${message(code: 'event.title.label', default: 'Title')}" />

                            <g:sortableColumn property="description" title="${message(code: 'event.description.label', default: 'Description')}" />

                            <g:sortableColumn property="date" title="${message(code: 'event.date.label', default: 'Time')}" />

                            <g:sortableColumn property="repeat" title="${message(code: 'event.repeat.label', default: 'Repeat')}" />

                        </tr>
                    </thead>
                    <tbody>
                    <g:each in="${todayEventsList}" status="i" var="eventInstance">
                        <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                            <td><g:link action="show" id="${eventInstance.id}">${fieldValue(bean: eventInstance, field: "title")}</g:link></td>

                            <td>${fieldValue(bean: eventInstance, field: "description")}</td>

                            <td><g:formatDate format="HH:mm" date="${eventInstance.date}" /></td>

                            <td>${fieldValue(bean: eventInstance, field: "repeat")}</td>

                        </tr>
                    </g:each>
                    </tbody>
                </table>
            </g:if>
            <g:if test="${tomorrowEventsList?.size()>0}">
                <h1 style="padding-left: 20px;">Events for tomorrow:</h1>
                <table>
                    <thead>
                    <tr>

                        <g:sortableColumn property="title" title="${message(code: 'event.title.label', default: 'Title')}" />

                        <g:sortableColumn property="description" title="${message(code: 'event.description.label', default: 'Description')}" />

                        <g:sortableColumn property="date" title="${message(code: 'event.date.label', default: 'Time')}" />

                        <g:sortableColumn property="repeat" title="${message(code: 'event.repeat.label', default: 'Repeat')}" />

                    </tr>
                    </thead>
                    <tbody>
                    <g:each in="${tomorrowEventsList}" status="i" var="eventInstance">
                        <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                            <td><g:link action="show" id="${eventInstance.id}">${fieldValue(bean: eventInstance, field: "title")}</g:link></td>

                            <td>${fieldValue(bean: eventInstance, field: "description")}</td>

                            <td><g:formatDate format="HH:mm" date="${eventInstance.date}" /></td>

                            <td>${fieldValue(bean: eventInstance, field: "repeat")}</td>

                        </tr>
                    </g:each>
                    </tbody>
                </table>
                <br>
                <br>
            </g:if>
            <h1 style="padding-left: 20px;">Choose date to browse events:</h1>
            <g:form url="[resource:event, action:'browseday']" method="GET" >
                <div class="fieldcontain required">
                    <label for="date">
                        <g:message default="Choose date to show events:" />
                    </label>
                    <g:datePicker name="date" precision="day" />
                    <input type="submit" value="Show" />
                </div>
            </g:form>
		</div>
	</body>
</html>

grails-app/views/event/show.gsp
<%@ page import="eventsplanningsystem.Event" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'event.label', default: 'Event')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-event" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-event" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list event">
			
				<g:if test="${eventInstance?.title}">
				<li class="fieldcontain">
					<span id="title-label" class="property-label"><g:message code="event.title.label" default="Title" /></span>
					
						<span class="property-value" aria-labelledby="title-label"><g:fieldValue bean="${eventInstance}" field="title"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${eventInstance?.description}">
				<li class="fieldcontain">
					<span id="description-label" class="property-label"><g:message code="event.description.label" default="Description" /></span>
					
						<span class="property-value" aria-labelledby="description-label"><g:fieldValue bean="${eventInstance}" field="description"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${eventInstance?.date}">
				<li class="fieldcontain">
					<span id="date-label" class="property-label"><g:message code="event.date.label" default="Date" /></span>
					
						<span class="property-value" aria-labelledby="date-label"><g:formatDate date="${eventInstance?.date}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${eventInstance?.repeat}">
				<li class="fieldcontain">
					<span id="repeat-label" class="property-label"><g:message code="event.repeat.label" default="Repeat" /></span>
					
						<span class="property-value" aria-labelledby="repeat-label"><g:fieldValue bean="${eventInstance}" field="repeat"/></span>
					
				</li>
				</g:if>

			
			</ol>
			<g:form url="[resource:eventInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${eventInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Grails"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="${resource(dir: 'images', file: 'favicon.ico')}" type="image/x-icon">
		<link rel="apple-touch-icon" href="${resource(dir: 'images', file: 'apple-touch-icon.png')}">
		<link rel="apple-touch-icon" sizes="114x114" href="${resource(dir: 'images', file: 'apple-touch-icon-retina.png')}">
		<link rel="stylesheet" href="${resource(dir: 'css', file: 'main.css')}" type="text/css">
		<link rel="stylesheet" href="${resource(dir: 'css', file: 'mobile.css')}" type="text/css">
		<g:layoutHead/>
		<g:javascript library="application"/>		
		<r:layoutResources />
	</head>
	<body>
		<div id="grailsLogo" role="banner"><a href="http://grails.org"><img src="${resource(dir: 'images', file: 'grails_logo.png')}" alt="Grails"/></a></div>
		<g:layoutBody/>
		<div class="footer" role="contentinfo"></div>
		<div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
		<r:layoutResources />
	</body>
</html>

grails-app/views/login/auth.gsp
<html>
<head>
	<meta name='layout' content='main'/>
	<title><g:message code="springSecurity.login.title"/></title>
	<style type='text/css' media='screen'>
	#login {
		margin: 15px 0px;
		padding: 0px;
		text-align: center;
	}

	#login .inner {
		width: 340px;
		padding-bottom: 6px;
		margin: 60px auto;
		text-align: left;
		border: 1px solid #aab;
		background-color: #f0f0fa;
		-moz-box-shadow: 2px 2px 2px #eee;
		-webkit-box-shadow: 2px 2px 2px #eee;
		-khtml-box-shadow: 2px 2px 2px #eee;
		box-shadow: 2px 2px 2px #eee;
	}

	#login .inner .fheader {
		padding: 18px 26px 14px 26px;
		background-color: #f7f7ff;
		margin: 0px 0 14px 0;
		color: #2e3741;
		font-size: 18px;
		font-weight: bold;
	}

	#login .inner .cssform p {
		clear: left;
		margin: 0;
		padding: 4px 0 3px 0;
		padding-left: 105px;
		margin-bottom: 20px;
		height: 1%;
	}

	#login .inner .cssform input[type='text'] {
		width: 120px;
	}

	#login .inner .cssform label {
		font-weight: bold;
		float: left;
		text-align: right;
		margin-left: -105px;
		width: 110px;
		padding-top: 3px;
		padding-right: 10px;
	}

	#login #remember_me_holder {
		padding-left: 120px;
	}

	#login #submit {
		margin-left: 15px;
	}

	#login #remember_me_holder label {
		float: none;
		margin-left: 0;
		text-align: left;
		width: 200px
	}

	#login .inner .login_message {
		padding: 6px 25px 20px 25px;
		color: #c33;
	}

	#login .inner .text_ {
		width: 120px;
	}

	#login .inner .chk {
		height: 12px;
	}
	</style>
</head>

<body>
<div id='login'>
	<div class='inner'>
		<div class='fheader'><g:message code="springSecurity.login.header"/></div>

		<g:if test='${flash.message}'>
			<div class='login_message'>${flash.message}</div>
		</g:if>

		<form action='${postUrl}' method='POST' id='loginForm' class='cssform' autocomplete='off'>
			<p>
				<label for='username'><g:message code="springSecurity.login.username.label"/>:</label>
				<input type='text' class='text_' name='j_username' id='username'/>
			</p>

			<p>
				<label for='password'><g:message code="springSecurity.login.password.label"/>:</label>
				<input type='password' class='text_' name='j_password' id='password'/>
			</p>

			<p id="remember_me_holder">
				<input type='checkbox' class='chk' name='${rememberMeParameter}' id='remember_me' <g:if test='${hasCookie}'>checked='checked'</g:if>/>
				<label for='remember_me'><g:message code="springSecurity.login.remember.me.label"/></label>
			</p>

			<p>
				<input type='submit' id="submit" value='${message(code: "springSecurity.login.button")}'/>
                <g:link controller="registration" action="index">Sign up</g:link>
			</p>
		</form>
	</div>
</div>
<script type='text/javascript'>
	<!--
	(function() {
		document.forms['loginForm'].elements['j_username'].focus();
	})();
	// -->
</script>
</body>
</html>